@startuml name
left to right direction

actor "Admin" as fc
actor "Student" as user

rectangle "Image editor" {
  usecase "CRUD Image" as UC1
  usecase "ADD Icons" as UC2
  usecase "Delete Icons" as UC3
 
  usecase "Update Image" as UC5
  usecase "ADD Image" as UC6
  usecase "Delete Image" as UC7
}

fc -- UC1
fc -- UC2
fc -- UC3

user -- UC5
user -- UC6
user -- UC7

@enduml
